version: '3'

services:
  statsd-exporter:
    image: prom/statsd-exporter
    container_name: airflow-statsd-exporter
    command: "--statsd.listen-udp=:8125 --web.listen-address=:9102 --log.level debug --statsd.mapping-config=/home/statsd-mapping-configs.yaml"
    ports:
      - 9123:9102
      - 8125:8125/udp
    volumes:
      - ./statsd-exporter/statsd.yaml:/home/statsd-mapping-configs.yaml
    networks:
      - airflow-networks

  prometheus:
    image: prom/prometheus
    container_name: airflow-prometheus
    user: "0"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - airflow-networks

  grafana:
    image: grafana/grafana
    container_name: airflow-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_PATHS_PROVISIONING: /grafana/provisioning
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/grafana/datasources
      - ./grafana/dashboards:/grafana/dashboards
      - ./grafana/provisioning:/grafana/provisioning
    networks:
      - airflow-networks

networks:
  airflow-networks:
    external: True