version: '1'
services:  

  warehouse-db-fp:
    image: postgres:latest
    container_name: warehousefp
    environment:
      POSTGRES_USER: ${SOURCE_DB_USER}
      POSTGRES_PASSWORD: ${SOURCE_DB_PASSWORD}
      POSTGRES_DB: ${SOURCE_DB_NAME}
    ports:
      - 5446:5432
    volumes:
      - ./init/dwh:/docker-entrypoint-initdb.d
      - warehouse-db-fp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SOURCE_DB_USER}"]
      interval: 5s
    restart: always
    networks:
      - airflow-networks


volumes:
  warehouse-db-fp:
    driver: local
    name: warehouse-db-fp


networks:
  airflow-networks:
    external: True